[package]
name = "wcip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pobsd-parser = { path = "../pobsd-parser" }
pobsd-db = { path = "../pobsd-db" }
attohttpc = "0.24.1"
