name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu/
  OPENSSL_INCLUDE_DIR: /usr/include/x86_64-linux-gnu/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
